backend:
  image: registry.relizahub.com/fab66fbc-5497-44d8-98e9-de781a51a8e0-public/mafia-express@sha256:bb3254832736a06474a833575c01a91d42749c81a0fe1671fb190b03c322a236
  replicaCount: 1
  port: 3000
  targetPort: 3000
ui:
  image: registry.relizahub.com/fab66fbc-5497-44d8-98e9-de781a51a8e0-public/mafia-vue@sha256:55cfc94c9b2cbae49bee48d86c9fc3e81db11709af0c92c26e3ab9935629e74e
  replicaCount: 1
  port: 80
  targetPort: 80
redis:
  image: docker.io/library/redis:6.2.3-buster
ingress:
  minimalIngressEnabled: true
  nginxEnabled: false
  traefikEnabled: false
  host: localhost